development: &defaults
  adapter: postgresql
  database: visa_development
  pool: 5

test: &test
  <<: *defaults
  database: visa_test

production:
  <<: *defaults
  database: visa_production

cucumber:
  <<: *test
